# Generated by Django 3.1.1 on 2020-11-03 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environments',
            name='User_Foreignkey',
        ),
        migrations.AddField(
            model_name='environments',
            name='UserInEnvironments',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
