# Generated by Django 3.1.1 on 2020-11-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environments', '0003_auto_20201103_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environments',
            name='UserInEnvironments',
        ),
        migrations.CreateModel(
            name='UserInEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Env_Key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='environments.environments')),
                ('User_Key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
