# Generated by Django 3.0.3 on 2020-09-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200902_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ph_num',
            field=models.CharField(max_length=10, verbose_name='phone number'),
        ),
    ]
