# Generated by Django 3.0.3 on 2020-09-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200902_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='l_name',
        ),
    ]
